/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSentimentRouteImport } from './routes/_app.sentiment'
import { Route as AppSandboxRouteImport } from './routes/_app.sandbox'
import { Route as AppMethodologyRouteImport } from './routes/_app.methodology'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppDeepDiveRouteImport } from './routes/_app.deep-dive'
import { Route as AppCorrelationRouteImport } from './routes/_app.correlation'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSentimentRoute = AppSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodologyRoute = AppMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDeepDiveRoute = AppDeepDiveRouteImport.update({
  id: '/deep-dive',
  path: '/deep-dive',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrelationRoute = AppCorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/alerts': typeof AppAlertsRoute
  '/correlation': typeof AppCorrelationRoute
  '/deep-dive': typeof AppDeepDiveRoute
  '/import': typeof AppImportRoute
  '/methodology': typeof AppMethodologyRoute
  '/sandbox': typeof AppSandboxRoute
  '/sentiment': typeof AppSentimentRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof AppAlertsRoute
  '/correlation': typeof AppCorrelationRoute
  '/deep-dive': typeof AppDeepDiveRoute
  '/import': typeof AppImportRoute
  '/methodology': typeof AppMethodologyRoute
  '/sandbox': typeof AppSandboxRoute
  '/sentiment': typeof AppSentimentRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/correlation': typeof AppCorrelationRoute
  '/_app/deep-dive': typeof AppDeepDiveRoute
  '/_app/import': typeof AppImportRoute
  '/_app/methodology': typeof AppMethodologyRoute
  '/_app/sandbox': typeof AppSandboxRoute
  '/_app/sentiment': typeof AppSentimentRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/correlation'
    | '/deep-dive'
    | '/import'
    | '/methodology'
    | '/sandbox'
    | '/sentiment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/correlation'
    | '/deep-dive'
    | '/import'
    | '/methodology'
    | '/sandbox'
    | '/sentiment'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/alerts'
    | '/_app/correlation'
    | '/_app/deep-dive'
    | '/_app/import'
    | '/_app/methodology'
    | '/_app/sandbox'
    | '/_app/sentiment'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sentiment': {
      id: '/_app/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof AppSentimentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/methodology': {
      id: '/_app/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof AppMethodologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deep-dive': {
      id: '/_app/deep-dive'
      path: '/deep-dive'
      fullPath: '/deep-dive'
      preLoaderRoute: typeof AppDeepDiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correlation': {
      id: '/_app/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof AppCorrelationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCorrelationRoute: typeof AppCorrelationRoute
  AppDeepDiveRoute: typeof AppDeepDiveRoute
  AppImportRoute: typeof AppImportRoute
  AppMethodologyRoute: typeof AppMethodologyRoute
  AppSandboxRoute: typeof AppSandboxRoute
  AppSentimentRoute: typeof AppSentimentRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCorrelationRoute: AppCorrelationRoute,
  AppDeepDiveRoute: AppDeepDiveRoute,
  AppImportRoute: AppImportRoute,
  AppMethodologyRoute: AppMethodologyRoute,
  AppSandboxRoute: AppSandboxRoute,
  AppSentimentRoute: AppSentimentRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
